# Generated by Django 6.0.1 on 2026-01-13 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('FOO', 'Food'), ('TRA', 'Transport'), ('ENT', 'Entertainment'), ('BIL', 'Bills'), ('EMI', 'EMI'), ('OTH', 'Other')], default='OTH', max_length=3)),
                ('frequency', models.CharField(choices=[('MON', 'Monthly'), ('WEK', 'Weekly')], default='MON', max_length=3)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('last_processed_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
