# Generated by Django 6.0.1 on 2026-01-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_recurringexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringexpense',
            name='payment_date',
            field=models.IntegerField(default=1, help_text='Day of the month (1-31) when this is due'),
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='recurrence_type',
            field=models.CharField(choices=[('BILL', 'Bill/Subscription'), ('SIP', 'SIP / Investment')], default='BILL', max_length=4),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='category',
            field=models.CharField(blank=True, choices=[('FOO', 'Food'), ('TRA', 'Transport'), ('ENT', 'Entertainment'), ('BIL', 'Bills'), ('EMI', 'EMI'), ('OTH', 'Other')], max_length=3, null=True),
        ),
    ]
