# Generated by Django 6.0 on 2026-01-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Annual Interest Rate in %', max_digits=5)),
                ('tenure_months', models.IntegerField(help_text='Loan Tenure in Months')),
                ('start_date', models.DateField()),
            ],
        ),
    ]
