# Generated by Django 6.0.1 on 2026-01-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID from external provider like Experian', max_length=50, null=True, unique=True),
        ),
    ]
