# Generated by Django 6.0.1 on 2026-01-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_investment_saving'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID from external broker', max_length=50, null=True, unique=True),
        ),
    ]
