# Generated by Django 6.0.1 on 2026-01-12 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_investment_external_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringWealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('SAV', 'Saving'), ('INV', 'Investment')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frequency', models.CharField(choices=[('MON', 'Monthly'), ('WEK', 'Weekly')], default='MON', max_length=3)),
                ('category', models.CharField(blank=True, choices=[('STK', 'Stocks'), ('MF', 'Mutual Funds'), ('GLD', 'Gold'), ('FD', 'Fixed Deposit'), ('RE', 'Real Estate'), ('CRY', 'Crypto'), ('OTH', 'Other')], max_length=3, null=True)),
                ('last_processed_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
