# Generated by Django 6.0.1 on 2026-01-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='manual_emi_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='manual_investment_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='manual_policy_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
