# Generated by Django 6.0.1 on 2026-01-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_investment_quantity_loan_benchmark_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('TERM', 'Term Insurance'), ('HEALTH', 'Health Insurance'), ('VEHICLE', 'Vehicle Insurance'), ('OTHER', 'Other')], default='TERM', max_length=10)),
                ('sum_assured', models.DecimalField(decimal_places=2, max_digits=12)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=12)),
                ('premium_date', models.DateField(help_text='Next Premium Due Date')),
            ],
        ),
    ]
