# Generated by Django 6.0.1 on 2026-01-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='current_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current Market Value', max_digits=12),
        ),
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Invested Amount', max_digits=12),
        ),
    ]
