# Generated by Django 6.0.1 on 2026-01-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_investment_current_value_alter_investment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vault_pin',
            field=models.CharField(blank=True, help_text='4-digit PIN for Document Vault', max_length=4, null=True),
        ),
    ]
