# Generated by Django 6.0.1 on 2026-08-03 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffordabilityQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_type', models.CharField(choices=[('LUMP_SUM', 'Lump Sum'), ('EMI', 'EMI / Financing')], default='LUMP_SUM', max_length=10)),
                ('decision', models.CharField(choices=[('YES', 'Yes, Affordable'), ('WAIT', 'Wait & Save'), ('NO', 'Not Affordable')], max_length=10)),
                ('affordability_score', models.FloatField()),
                ('explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affordability_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SAVINGS', 'Savings & Liquid Fund'), ('DEBT', 'Debt & EMI Management'), ('INVESTMENT', 'Investments & Growth'), ('SPENDING', 'Budget & Outflow Optimization'), ('EMERGENCY_FUND', 'Emergency Preparedness')], max_length=20)),
                ('priority', models.CharField(choices=[('HIGH', 'High Priority'), ('MEDIUM', 'Medium Priority'), ('LOW', 'Low Priority')], default='MEDIUM', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('action_url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_saved', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('target_date', models.DateField()),
                ('category', models.CharField(choices=[('VEHICLE', 'Vehicle (Bike/Car)'), ('ELECTRONICS', 'Electronics (Laptop/Phone)'), ('VACATION', 'Travel & Vacation'), ('EMERGENCY', 'Emergency Fund'), ('HOUSE', 'Real Estate / House'), ('OTHER', 'Other Goal')], default='OTHER', max_length=20)),
                ('priority', models.CharField(choices=[('HIGH', 'High Priority'), ('MEDIUM', 'Medium Priority'), ('LOW', 'Low Priority')], default='MEDIUM', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['target_date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialHealthHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('status', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('CRITICAL', 'Critical')], max_length=10)),
                ('dti_ratio', models.FloatField()),
                ('savings_ratio', models.FloatField()),
                ('expense_ratio', models.FloatField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
    ]
